name: Release Binary

on:
  push:
    tags:
      - 'v*' # Nur bei Tags wie v1.0.0

permissions:
  contents: write

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo build
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build release binary
        run: cargo build --release

      - name: Strip debug symbols (optional, für kleinere Größe)
        run: strip target/release/mac-updater || true

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/mac-updater
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
